name: Build and publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - frontend/**

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20.9
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        working-directory: ./frontend/
        run: yarn

      - name: Build project
        working-directory: ./frontend/
        run: yarn run build

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        working-directory: ./frontend/
        with:
          inlineScript: |
            az storage blob upload-batch --account-name magellodashmapstorage --auth-mode key -d '$web' -s build/

      - name: Azure logout
        run: |
          az logout
        if: always()
