name: "[BE] Build and publish"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/**

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Java version 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build project
        working-directory: ./backend
        run: ./gradlew buildDockerImage

      - name: Login to Azure container registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push container image
        run: |
          docker tag magello-dashmap:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/magello-dashmap-be:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/magello-dashmap-be:latest

      - name: Azure logout
        run: |
          az logout
        if: always()
