name: "[FE] Build and publish"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - frontend/**

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Use Node.js 20.9
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Build dependency react-search-autocomplete
        working-directory: ./react-search-autocomplete
        run: yarn && yarn run build && rm -rf node_modules/

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn

      - name: Build project
        working-directory: ./frontend
        run: yarn run build

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create needed directories in file shares
        uses: azure/CLI@v1
        with:
          inlineScript: |
            for i in $(find frontend/build/ -type d -print); do i=${i#frontend/build/}; if [ ! -z $i ]; then az storage directory create --account-name magellodashmapstorage --share-name temp --name "$i" --output none; if [ $? -ne 0 ]; then break; fi; fi; done

      - name: Upload files to file shares
        uses: azure/CLI@v1
        with:
          inlineScript: |
            for i in $(find frontend/build/ -type f -print); do az storage file upload --account-name magellodashmapstorage --share-name temp --source "$i" --path "${i#frontend/build/}"; if [ $? -ne 0 ]; then break; fi; done

      - name: Azure logout
        run: |
          az logout
        if: always()
